# name: Feature-based Branching and Deployment
# on:
#   push:
#     branches: [ "main" ]
# jobs:
#   deploy:
#     name: python
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3
# #     - name: updating
# #       run: sudo apt update
# #     - name: installing
# #       run: sudo apt install python3
# #     - name: directory
# #       run: mkdir python
# #     - name: moving file
# #       run: cp sample.py pyhton
# #     - name: chaning
# #       run: cd python
#     - name: permission
#       run: chmod +x sample.py
#     - name: pythonscript
#       run: python3 sample.py


name: Feature-based Branching and Deployment
on: 
  push:
    branches:
      - feature

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Python application1
        run: python sample.py
