name: Feature-based Branching and Deployment
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: updating
      run: sudo apt update
    - name: installing
      run: sudo apt install python3
    - name: permission
      run: chmod g+x sample.py
    - name: pythonscript
      run: ./sample.py
