name: Feature-based Branching and Deployment
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: python
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: updating
      run: sudo apt update
    - name: installing
      run: sudo apt install python3
    - name: directory
      run: mkdir python
    - name: moving file
      run: cp sample.py pyhton
    - name: chaning
      run: cd python
    - name: permission
      run: chmod +x sample.py
    - name: pythonscript
      run: python3 sample.py
